server:
  servlet:
    contextPath:  /intraway/api/

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/fizzbuzz
    username: root
    password: s3cr3t

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources.add-mappings: false

