server:
  servlet:
    contextPath:  /intraway/api/
  error:
    path: /error
  #  include-exception: true
   # include-stacktrace: never

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/fizzbuzz
    username: root
    password: s3cr3t
    #driver-class-name: com.mysql.jdbc.Driver
